"""create product service tables

Revision ID: 13a15613bc8d
Revises: 
Create Date: 2026-10-06 11:45:25.027710

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '13a15613bc8d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attributes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attributes')),
    sa.UniqueConstraint('name', name=op.f('uq_attributes_name'))
    )
    op.create_index(op.f('ix_attributes_id'), 'attributes', ['id'], unique=False)
    op.create_table('attribute_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_attribute_values_attribute_id_attributes')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attribute_values')),
    sa.UniqueConstraint('attribute_id', 'value', name='uq_attribute_value')
    )
    op.create_index(op.f('ix_attribute_values_id'), 'attribute_values', ['id'], unique=False)
    op.create_table('product_attributes',
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('attribute_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_id'], ['attributes.id'], name=op.f('fk_product_attributes_attribute_id_attributes')),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_product_attributes_product_id_products')),
    sa.PrimaryKeyConstraint('product_id', 'attribute_id', name=op.f('pk_product_attributes'))
    )
    op.create_table('variant_attribute_values',
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('attribute_value_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['attribute_value_id'], ['attribute_values.id'], name=op.f('fk_variant_attribute_values_attribute_value_id_attribute_values')),
    sa.ForeignKeyConstraint(['variant_id'], ['product_variants.id'], name=op.f('fk_variant_attribute_values_variant_id_product_variants')),
    sa.PrimaryKeyConstraint('variant_id', 'attribute_value_id', name=op.f('pk_variant_attribute_values'))
    )
    op.drop_index(op.f('name'), table_name='categories')
    op.create_unique_constraint(op.f('uq_categories_name'), 'categories', ['name'])
    op.add_column('product_variants', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('product_variants', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('product_variants', 'stock',
               existing_type=mysql.INTEGER(),
               nullable=False)
    op.create_unique_constraint(op.f('uq_product_variants_sku'), 'product_variants', ['sku'])
    op.create_foreign_key(op.f('fk_product_variants_product_id_products'), 'product_variants', 'products', ['product_id'], ['id'])
    op.alter_column('products', 'is_active',
               existing_type=mysql.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True)
    op.create_foreign_key(op.f('fk_products_category_id_categories'), 'products', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_category_id_categories'), 'products', type_='foreignkey')
    op.alter_column('products', 'is_active',
               existing_type=sa.Boolean(),
               type_=mysql.INTEGER(),
               existing_nullable=True)
    op.drop_constraint(op.f('fk_product_variants_product_id_products'), 'product_variants', type_='foreignkey')
    op.drop_constraint(op.f('uq_product_variants_sku'), 'product_variants', type_='unique')
    op.alter_column('product_variants', 'stock',
               existing_type=mysql.INTEGER(),
               nullable=True)
    op.drop_column('product_variants', 'updated_at')
    op.drop_column('product_variants', 'created_at')
    op.drop_constraint(op.f('uq_categories_name'), 'categories', type_='unique')
    op.create_index(op.f('name'), 'categories', ['name'], unique=True)
    op.drop_table('variant_attribute_values')
    op.drop_table('product_attributes')
    op.drop_index(op.f('ix_attribute_values_id'), table_name='attribute_values')
    op.drop_table('attribute_values')
    op.drop_index(op.f('ix_attributes_id'), table_name='attributes')
    op.drop_table('attributes')
    # ### end Alembic commands ###
